/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    users: User
    media: Media
    categories: Category
    tags: Tag
    posts: Post
    pages: Page
    'audit-logs': AuditLog
    forms: Form
    'form-submissions': FormSubmission
    search: Search
    'payload-kv': PayloadKv
    'payload-jobs': PayloadJob
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {}
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    categories: CategoriesSelect<false> | CategoriesSelect<true>
    tags: TagsSelect<false> | TagsSelect<true>
    posts: PostsSelect<false> | PostsSelect<true>
    pages: PagesSelect<false> | PagesSelect<true>
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>
    forms: FormsSelect<false> | FormsSelect<true>
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>
    search: SearchSelect<false> | SearchSelect<true>
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: number
  }
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('fr' | 'en' | 'nl')
    | ('fr' | 'en' | 'nl')[]
  globals: {}
  globalsSelect: {}
  locale: 'fr' | 'en' | 'nl'
  widgets: {
    collections: CollectionsWidget
  }
  user: User
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish
      inline: {
        input: unknown
        output: unknown
      }
    }
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number
  roles: ('admin' | 'editor' | 'user')[]
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  sessions?:
    | {
        id: string
        createdAt?: string | null
        expiresAt: string
      }[]
    | null
  password?: string | null
  collection: 'users'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number
  alt: string
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number
  label: string
  slug?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number
  label: string
  slug?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number
  title: string
  slug?: string | null
  /**
   * Short summary displayed in post listings
   */
  excerpt?: string | null
  content?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  featuredImage?: (number | null) | Media
  author?: (number | null) | User
  category?: (number | null) | Category
  tags?: (number | Tag)[] | null
  status?: ('draft' | 'review' | 'published') | null
  publishedAt?: string | null
  meta?: {
    title?: string | null
    description?: string | null
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media
  }
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number
  title: string
  slug?: string | null
  layout: (
    | {
        heading: string
        subheading?: string | null
        backgroundImage?: (number | null) | Media
        ctaLabel?: string | null
        ctaLink?: string | null
        id?: string | null
        blockName?: string | null
        blockType: 'hero'
      }
    | {
        richText: {
          root: {
            type: string
            children: {
              type: any
              version: number
              [k: string]: unknown
            }[]
            direction: ('ltr' | 'rtl') | null
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
            indent: number
            version: number
          }
          [k: string]: unknown
        }
        id?: string | null
        blockName?: string | null
        blockType: 'content'
      }
    | {
        steps: {
          /**
           * Icon name or emoji for this step
           */
          icon?: string | null
          title: string
          description: string
          id?: string | null
        }[]
        id?: string | null
        blockName?: string | null
        blockType: 'howItWorks'
      }
    | {
        profiles: {
          title: string
          description: string
          image?: (number | null) | Media
          id?: string | null
        }[]
        id?: string | null
        blockName?: string | null
        blockType: 'targetAudience'
      }
    | {
        items: {
          question: string
          answer: {
            root: {
              type: string
              children: {
                type: any
                version: number
                [k: string]: unknown
              }[]
              direction: ('ltr' | 'rtl') | null
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
              indent: number
              version: number
            }
            [k: string]: unknown
          }
          id?: string | null
        }[]
        id?: string | null
        blockName?: string | null
        blockType: 'faq'
      }
    | {
        testimonials: {
          name: string
          role?: string | null
          quote: string
          photo?: (number | null) | Media
          id?: string | null
        }[]
        id?: string | null
        blockName?: string | null
        blockType: 'testimonials'
      }
    | {
        heading: string
        description?: string | null
        buttonLabel: string
        buttonLink: string
        id?: string | null
        blockName?: string | null
        blockType: 'cta'
      }
    | {
        images: {
          image: number | Media
          caption?: string | null
          id?: string | null
        }[]
        id?: string | null
        blockName?: string | null
        blockType: 'imageGallery'
      }
  )[]
  status?: ('draft' | 'review' | 'published') | null
  publishedAt?: string | null
  meta?: {
    title?: string | null
    description?: string | null
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media
  }
  parent?: (number | null) | Page
  breadcrumbs?:
    | {
        doc?: (number | null) | Page
        url?: string | null
        label?: string | null
        id?: string | null
      }[]
    | null
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number
  collection: string
  documentId: string
  action: 'create' | 'update' | 'delete'
  user?: (number | null) | User
  before?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  after?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number
  title: string
  fields?:
    | (
        | {
            name: string
            label?: string | null
            width?: number | null
            required?: boolean | null
            defaultValue?: boolean | null
            id?: string | null
            blockName?: string | null
            blockType: 'checkbox'
          }
        | {
            name: string
            label?: string | null
            width?: number | null
            required?: boolean | null
            id?: string | null
            blockName?: string | null
            blockType: 'country'
          }
        | {
            name: string
            label?: string | null
            width?: number | null
            required?: boolean | null
            id?: string | null
            blockName?: string | null
            blockType: 'email'
          }
        | {
            message?: {
              root: {
                type: string
                children: {
                  type: any
                  version: number
                  [k: string]: unknown
                }[]
                direction: ('ltr' | 'rtl') | null
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
                indent: number
                version: number
              }
              [k: string]: unknown
            } | null
            id?: string | null
            blockName?: string | null
            blockType: 'message'
          }
        | {
            name: string
            label?: string | null
            width?: number | null
            defaultValue?: number | null
            required?: boolean | null
            id?: string | null
            blockName?: string | null
            blockType: 'number'
          }
        | {
            name: string
            label?: string | null
            width?: number | null
            defaultValue?: string | null
            placeholder?: string | null
            options?:
              | {
                  label: string
                  value: string
                  id?: string | null
                }[]
              | null
            required?: boolean | null
            id?: string | null
            blockName?: string | null
            blockType: 'select'
          }
        | {
            name: string
            label?: string | null
            width?: number | null
            required?: boolean | null
            id?: string | null
            blockName?: string | null
            blockType: 'state'
          }
        | {
            name: string
            label?: string | null
            width?: number | null
            defaultValue?: string | null
            required?: boolean | null
            id?: string | null
            blockName?: string | null
            blockType: 'text'
          }
        | {
            name: string
            label?: string | null
            width?: number | null
            defaultValue?: string | null
            required?: boolean | null
            id?: string | null
            blockName?: string | null
            blockType: 'textarea'
          }
      )[]
    | null
  submitButtonLabel?: string | null
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null
  confirmationMessage?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  redirect?: {
    url: string
  }
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null
        cc?: string | null
        bcc?: string | null
        replyTo?: string | null
        emailFrom?: string | null
        subject: string
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string
            children: {
              type: any
              version: number
              [k: string]: unknown
            }[]
            direction: ('ltr' | 'rtl') | null
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
            indent: number
            version: number
          }
          [k: string]: unknown
        } | null
        id?: string | null
      }[]
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number
  form: number | Form
  submissionData?:
    | {
        field: string
        value: string
        id?: string | null
      }[]
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number
  title?: string | null
  priority?: number | null
  doc:
    | {
        relationTo: 'posts'
        value: number | Post
      }
    | {
        relationTo: 'pages'
        value: number | Page
      }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number
  key: string
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  taskStatus?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  completedAt?: string | null
  totalTried?: number | null
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string
        completedAt: string
        taskSlug: 'inline' | 'schedulePublish'
        taskID: string
        input?:
          | {
              [k: string]: unknown
            }
          | unknown[]
          | string
          | number
          | boolean
          | null
        output?:
          | {
              [k: string]: unknown
            }
          | unknown[]
          | string
          | number
          | boolean
          | null
        state: 'failed' | 'succeeded'
        error?:
          | {
              [k: string]: unknown
            }
          | unknown[]
          | string
          | number
          | boolean
          | null
        id?: string | null
      }[]
    | null
  taskSlug?: ('inline' | 'schedulePublish') | null
  queue?: string | null
  waitUntil?: string | null
  processing?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number
  document?:
    | ({
        relationTo: 'users'
        value: number | User
      } | null)
    | ({
        relationTo: 'media'
        value: number | Media
      } | null)
    | ({
        relationTo: 'categories'
        value: number | Category
      } | null)
    | ({
        relationTo: 'tags'
        value: number | Tag
      } | null)
    | ({
        relationTo: 'posts'
        value: number | Post
      } | null)
    | ({
        relationTo: 'pages'
        value: number | Page
      } | null)
    | ({
        relationTo: 'audit-logs'
        value: number | AuditLog
      } | null)
    | ({
        relationTo: 'forms'
        value: number | Form
      } | null)
    | ({
        relationTo: 'form-submissions'
        value: number | FormSubmission
      } | null)
    | ({
        relationTo: 'search'
        value: number | Search
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: number | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number
  user: {
    relationTo: 'users'
    value: number | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
  sessions?:
    | T
    | {
        id?: T
        createdAt?: T
        expiresAt?: T
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  label?: T
  slug?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  label?: T
  slug?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T
  slug?: T
  excerpt?: T
  content?: T
  featuredImage?: T
  author?: T
  category?: T
  tags?: T
  status?: T
  publishedAt?: T
  meta?:
    | T
    | {
        title?: T
        description?: T
        image?: T
      }
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T
  slug?: T
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T
              subheading?: T
              backgroundImage?: T
              ctaLabel?: T
              ctaLink?: T
              id?: T
              blockName?: T
            }
        content?:
          | T
          | {
              richText?: T
              id?: T
              blockName?: T
            }
        howItWorks?:
          | T
          | {
              steps?:
                | T
                | {
                    icon?: T
                    title?: T
                    description?: T
                    id?: T
                  }
              id?: T
              blockName?: T
            }
        targetAudience?:
          | T
          | {
              profiles?:
                | T
                | {
                    title?: T
                    description?: T
                    image?: T
                    id?: T
                  }
              id?: T
              blockName?: T
            }
        faq?:
          | T
          | {
              items?:
                | T
                | {
                    question?: T
                    answer?: T
                    id?: T
                  }
              id?: T
              blockName?: T
            }
        testimonials?:
          | T
          | {
              testimonials?:
                | T
                | {
                    name?: T
                    role?: T
                    quote?: T
                    photo?: T
                    id?: T
                  }
              id?: T
              blockName?: T
            }
        cta?:
          | T
          | {
              heading?: T
              description?: T
              buttonLabel?: T
              buttonLink?: T
              id?: T
              blockName?: T
            }
        imageGallery?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T
                    caption?: T
                    id?: T
                  }
              id?: T
              blockName?: T
            }
      }
  status?: T
  publishedAt?: T
  meta?:
    | T
    | {
        title?: T
        description?: T
        image?: T
      }
  parent?: T
  breadcrumbs?:
    | T
    | {
        doc?: T
        url?: T
        label?: T
        id?: T
      }
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  collection?: T
  documentId?: T
  action?: T
  user?: T
  before?: T
  after?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T
              label?: T
              width?: T
              required?: T
              defaultValue?: T
              id?: T
              blockName?: T
            }
        country?:
          | T
          | {
              name?: T
              label?: T
              width?: T
              required?: T
              id?: T
              blockName?: T
            }
        email?:
          | T
          | {
              name?: T
              label?: T
              width?: T
              required?: T
              id?: T
              blockName?: T
            }
        message?:
          | T
          | {
              message?: T
              id?: T
              blockName?: T
            }
        number?:
          | T
          | {
              name?: T
              label?: T
              width?: T
              defaultValue?: T
              required?: T
              id?: T
              blockName?: T
            }
        select?:
          | T
          | {
              name?: T
              label?: T
              width?: T
              defaultValue?: T
              placeholder?: T
              options?:
                | T
                | {
                    label?: T
                    value?: T
                    id?: T
                  }
              required?: T
              id?: T
              blockName?: T
            }
        state?:
          | T
          | {
              name?: T
              label?: T
              width?: T
              required?: T
              id?: T
              blockName?: T
            }
        text?:
          | T
          | {
              name?: T
              label?: T
              width?: T
              defaultValue?: T
              required?: T
              id?: T
              blockName?: T
            }
        textarea?:
          | T
          | {
              name?: T
              label?: T
              width?: T
              defaultValue?: T
              required?: T
              id?: T
              blockName?: T
            }
      }
  submitButtonLabel?: T
  confirmationType?: T
  confirmationMessage?: T
  redirect?:
    | T
    | {
        url?: T
      }
  emails?:
    | T
    | {
        emailTo?: T
        cc?: T
        bcc?: T
        replyTo?: T
        emailFrom?: T
        subject?: T
        message?: T
        id?: T
      }
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T
  submissionData?:
    | T
    | {
        field?: T
        value?: T
        id?: T
      }
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T
  priority?: T
  doc?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T
  data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T
  taskStatus?: T
  completedAt?: T
  totalTried?: T
  hasError?: T
  error?: T
  log?:
    | T
    | {
        executedAt?: T
        completedAt?: T
        taskSlug?: T
        taskID?: T
        input?: T
        output?: T
        state?: T
        error?: T
        id?: T
      }
  taskSlug?: T
  queue?: T
  waitUntil?: T
  processing?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown
  }
  width: 'full'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null
    locale?: string | null
    doc?: {
      relationTo: 'posts'
      value: number | Post
    } | null
    global?: string | null
    user?: (number | null) | User
  }
  output?: unknown
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
